// src/data.js
export const users = [
    {
        id: 1,
        name: "PSA loverrrrr",
        imageUrl: '/images/mentor1.jpg',
        age: "30",
        yearsOfExperience: "2",
        role: "Software Engineer",
        department: "Supply Management",
        location: "Singapore",
        tel: "88888888",
        email: "XXXXXXXX@gmail.com",
        skills: ["JavaScript", "React"],
        skillsToLearn: ["Node.js", "Python", "Marketing"],
        projects: ["PSA codesprint"],
    },

    {
        id: 2,
        name: "Tech Guru",
        imageUrl: '/images/mentor2.jpg',
        age: "35",
        yearsOfExperience: "5",
        role: "Senior Developer",
        department: "Engineering",
        location: "San Francisco",
        tel: "55555555",
        email: "techguru@gmail.com",
        skills: ["Python", "Django", "JavaScript"],
        skillsToLearn: ["Machine Learning", "AI", "Data Science"],
        projects: ["E-commerce Platform", "Data Analytics"]
    },
    {

        id: 3,
        name: "Code Ninja",
        imageUrl: '/images/mentor3.jpg',
        age: "28",
        yearsOfExperience: "3",
        role: "Full Stack Developer",
        department: "Technology",
        location: "New York",
        tel: "77777777",
        email: "codeninja@gmail.com",
        skills: ["Java", "Spring Boot", "Angular"],
        skillsToLearn: ["Cloud Computing", "DevOps"],
        projects: ["Inventory Management", "E-learning Platform"]
    },

    {
        id: 4,
        name: "Web Wizard",
        imageUrl: '/images/mentor4.jpg',
        age: "32",
        yearsOfExperience: "6",
        role: "UI/UX Designer",
        department: "Design",
        location: "London",
        tel: "66666666",
        email: "webwizard@gmail.com",
        skills: ["HTML", "CSS", "JavaScript"],
        skillsToLearn: ["Motion Graphics", "UI Animation"],
        projects: ["Website Redesign", "Mobile App UI"]
    },

    {
        id: 5,
        name: "Data Scientist",
        imageUrl: '/images/mentor5.jpg',
        age: "29",
        yearsOfExperience: "4",
        role: "Data Scientist",
        department: "Data Science",
        location: "Berlin",
        tel: "99999999",
        email: "datascientist@gmail.com",
        skills: ["Python", "R", "Machine Learning"],
        skillsToLearn: ["Big Data", "Natural Language Processing"],
        projects: ["Customer Segmentation", "Predictive Modeling"]
    },
    // Add more user data as needed
];

export const mentors = [
    {
        id: 1,
        name: "Amy Lim",
        imageUrl: '/images/mentor1.jpg',
        age: "25",
        yearsOfExperience: "5",
        role: "Algorithm Engineer",
        department: "Cargo Shipment",
        location: "Singapore",
        tel: "88888888",
        email: "XXXXXXXX@gmail.com",
        skills: ["JavaScript", "React", "Node.js"],
        skillsToLearn: ["HTML", "CSS"],
        projects: ["PSA codesprint", "Tuas Port"],
    },
    {
        id: 2,
        name: "Benny Tan",
        imageUrl: '/images/mentor1.jpg',
        yearsOfExperience: "6",
        role: "Algorithm Senior Engineer",
        department: "Supply Management",
        location: "Singapore",
        tel: "88888888",
        email: "XXXXXXXX@gmail.com",
        skills: ["Python", "Django", "Data Science", "Node.js"],
        skillsToLearn: ["Java", "Marketing"],
        projects: ["Tuas Port"],
    },
    {
        id: 3,
        name: "Charlie Chan",
        imageUrl: '/images/mentor1.jpg',
        yearsOfExperience: "7",
        role: "Product Manager",
        department: "Cargo Shipment",
        location: "Singapore",
        tel: "88888888",
        email: "XXXXXXXX@gmail.com",
        skills: ["Python", "Java", "Marketing", "Node.js", "Selenium"],
        skillsToLearn: ["Database", "Data Science"],
        projects: ["PSA codesprint", "Jurong Island Terminal"],
    },
    // Add more mentor data as needed
];
